name: Monorepo

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

jobs:
  monorepo-integrity:
    name: Check integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Node.js 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

      - name: 👬🏽 Check for duplicate dependencies in lock file
        run: yarn dedupe --check

      - name: 🦺 Check for yarn constraints.pro
        run: yarn constraints
